apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
             serviceName: frontend
             servicePort: 8080