apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-app
  labels:
    team: frontend
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: nginx-app
  endpoints:
  - port: metrics