apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  labels:
    app: nginx-app
spec:
  ports:
  - name: nginx
    protocol: TCP
    port: 80
  - name: metrics
    protocol: TCP
    port: 9113
  selector:
    app: nginx
  type: NodePort