environments:
  default:
    values:
    - domain: 35.228.138.157.nip.io
    - issuer: letsencrypt-staging
  production:
    values:
    - domain: 35.228.138.157.nip.io
    - issuer: letsencrypt-production

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: jetstack
  url: https://charts.jetstack.io
- name: harbor
  url: https://helm.goharbor.io

helmDefaults:
  wait: true

templates:
  template: &template
    missingFileHandler: Warn
    values:
    - ./values/{{`{{ .Release.Name }}`}}.yaml.gotmpl

releases:
- name: nginx-ingress
  namespace: nginx-ingress
  chart: stable/nginx-ingress
  version: 1.11.1
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: 0.9.0
  hooks:
  - events:
    #- prepare
    - presync
    showlogs: true
    #command: echo
    command: kubectl
    args:
    - apply
    - -f
    - https://raw.githubusercontent.com/jetstack/cert-manager/release-0.9/deploy/manifests/00-crds.yaml
  - events:
    #- prepare
    - presync
    showlogs: true
    #command: echo
    command: kubectl
    args:
    - label
    - namespace
    - "{{`{{ .Release.Namespace }}`}}"
    - certmanager.k8s.io/disable-validation="true"
  - events:
    #- cleanup
    - postsync
    showlogs: true
    #command: echo
    command: kubectl
    args:
    - apply
    - -f
    - kubernetes-templating/cert-manager/clusterissuer-{{ .Values.issuer }}.yaml
- name: harbor
  namespace: harbor
  chart: harbor/harbor
  version: 1.1.2
  values:
  <<: *template