apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-reverse
  labels:
    app: paymentservice-reverse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice-reverse
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: paymentservice-reverse
    spec:
      containers:
        - name: server
          image: revard/otus-k8s-paymentservice:v0.0.2
