alertmanager:
    alertmanagerSpec:
      tolerations: &tolerations
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    path: /
    hosts:
    - grafana.34.89.8.127.xip.io
  tolerations: *tolerations
  additionalDataSources:
  - name: Loki
    access: proxy
    type: loki
    url: http://loki:3100/