apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: revard/otus-k8s-frontend
    name: frontend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
